### ISSUE TITLE
关于easyMirai中同意新加群请求操作函数newJoinGroup的问题

### ISSUE THREAD

**Issue by hz3271** [easyMirais/easyMirai#10]
我在添加自动进群功能时出现了一个错误，提示TypeError: 'NoneType' object is not subscriptable
以下是详细信息：
Traceback (most recent call last):
  File "E:\pythonProject\qbot_test.py", line 326, in <module>
    chat_bot.run()
  File "E:\pythonProject\qbot_test.py", line 54, in run
    asyncio.run(self.main())
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "E:\pythonProject\qbot_test.py", line 62, in main
    await asyncio.gather(get_messages_task, process_messages_task)
  File "E:\pythonProject\qbot_test.py", line 83, in process_message_queue
    await self.process_messages(message_data)  # 处理消息
  File "E:\pythonProject\qbot_test.py", line 99, in process_messages
    await self.handle_message_type(messages, dict_data)
  File "E:\pythonProject\qbot_test.py", line 126, in handle_message_type
    await self.MemberJoinRequestEvent(message)
  File "E:\pythonProject\qbot_test.py", line 186, in MemberJoinRequestEvent
    self.newJoinGroup_fun(event_id, from_id, group_id)
  File "E:\pythonProject\qbot_test.py", line 219, in newJoinGroup_fun
    self.mirai.event(eventid).newJoinGroup(target, groupId).yes()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\easyMirai\eventType.py", line 124, in yes
    return self._request(1, self._eventId, message)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\easyMirai\eventType.py", line 105, in _request
    print(api["event"]["newFriend"])
TypeError: 'NoneType' object is not subscriptable

单独机器人测试是这样的，  
Traceback (most recent call last):
  File "E:\pythonProject\test3.py", line 69, in <module>
    chat_bot = ChatBot()
  File "E:\pythonProject\test3.py", line 64, in __init__
    self.mirai.event(1701770831044547).newJoinGroup(3505142595, 170858532).yes()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\easyMirai\eventType.py", line 124, in yes
    return self._request(1, self._eventId, message)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\easyMirai\eventType.py", line 105, in _request
    print(api["event"]["newFriend"])
TypeError: 'NoneType' object is not subscriptable

还请阁下指导一下是哪里出现了问题😊

**Comment by HexMikuMax** [comment]
方便提供一下源代码嘛🫣

**Comment by hz3271** [comment]
> 方便提供一下源代码嘛🫣

class ChatBot:
    def __init__(self):

        self.mirai = easyMirai.Mirai(host, port, qq, auth_key)
        self.send_type_mode_instance = self.mirai.send
        print(self.send_type_mode_instance)
        self.id_ = None
        self.text = None
        self.dict_data = None
        self.log = []

        self.get_message = GetMessage(
            uri=self.send_type_mode_instance._uri,
            session=self.send_type_mode_instance._session,
            isSlice=self.send_type_mode_instance._isSlice
        )
        self.mirai.send.friend(id).plain("你好").dictionary
        self.mirai.event(1701770831044547).newJoinGroup(3505142595, 170858532).yes()

if __name__ == '__main__':
            chat_bot = ChatBot()
单独拿出来是这样的，给好友和群发送消息是正常的，但是入群申请通过会报错

**Comment by HexMikuMax** [comment]
> > 方便提供一下源代码嘛🫣
> 
> class ChatBot: def **init**(self):
> 
> ```
>     self.mirai = easyMirai.Mirai(host, port, qq, auth_key)
>     self.send_type_mode_instance = self.mirai.send
>     print(self.send_type_mode_instance)
>     self.id_ = None
>     self.text = None
>     self.dict_data = None
>     self.log = []
> 
>     self.get_message = GetMessage(
>         uri=self.send_type_mode_instance._uri,
>         session=self.send_type_mode_instance._session,
>         isSlice=self.send_type_mode_instance._isSlice
>     )
>     self.mirai.send.friend(id).plain("你好").dictionary
>     self.mirai.event(1701770831044547).newJoinGroup(3505142595, 170858532).yes()
> ```
> 
> if **name** == '**main**': chat_bot = ChatBot() 单独拿出来是这样的，给好友和群发送消息是正常的，但是入群申请通过会报错

好的我和Ex在下午会修改这个问题尽量在晚上之前发布新的修改版本😊

**Comment by hz3271** [comment]
> > > 方便提供一下源代码嘛🫣
> > 
> > 
> > class ChatBot: def **init**(self):
> > ```
> >     self.mirai = easyMirai.Mirai(host, port, qq, auth_key)
> >     self.send_type_mode_instance = self.mirai.send
> >     print(self.send_type_mode_instance)
> >     self.id_ = None
> >     self.text = None
> >     self.dict_data = None
> >     self.log = []
> > 
> >     self.get_message = GetMessage(
> >         uri=self.send_type_mode_instance._uri,
> >         session=self.send_type_mode_instance._session,
> >         isSlice=self.send_type_mode_instance._isSlice
> >     )
> >     self.mirai.send.friend(id).plain("你好").dictionary
> >     self.mirai.event(1701770831044547).newJoinGroup(3505142595, 170858532).yes()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if **name** == '**main**': chat_bot = ChatBot() 单独拿出来是这样的，给好友和群发送消息是正常的，但是入群申请通过会报错
> 
> 好的我和Ex在下午会修改这个问题尽量在晚上之前发布新的修改版本😊

非常感谢！

**Comment by ExMikuPro** [comment]
请问使用Mirai框架相关都是哪个版本的？机器人实在登不上去

**Comment by hz3271** [comment]
> 请问使用Mirai框架相关都是哪个版本的？机器人实在登不上去

不好意思，看到得的时候我在下班回家路上，已经在qq上和您联系了

**Comment by HexMikuMax** [comment]
请使用 [这个](https://pypi.org/project/easyMirai/2.33.36/) v2.33.36版本的easyMiria库，非常抱歉拖了这么久😣，感谢使用easyMirai库～

**Comment by hz3271** [comment]
> 请使用 [这个](https://pypi.org/project/easyMirai/2.33.36/) v2.33.36版本的easyMiria库，非常抱歉拖了这么久😣，感谢使用easyMirai库～

哪里的事，非常感谢！
